[package]
name = "can_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
socketcan = { version = "3.3.0", features = ["tokio"] }
futures-util = "0.3.31"
tokio = { version = "1.37.0", features = ["full"] }
lazy_static = "1.5.0"
pid = "4.0.0"